### ISSUE TITLE
Add hunger

### ISSUE THREAD

**Issue by 0-afflatus** [0-afflatus/grailtest#4]
I'm in two minds about this.
Either something very simple and almost brutal rather than modding blockmen's mod or not at all.

**Comment by sofar** [comment]
No matter what, I'll end up making the hunger patch to minetest_game a separate mod that should work without additional dependencies.

**Comment by 0-afflatus** [comment]
Cool, that sounds like it could be ideal.

**Comment by sofar** [comment]
https://github.com/minetest-mods/stamina

**Comment by 0-afflatus** [comment]
Seen and cloned.
I shall put it through its paces and feed back.

**Comment by sofar** [comment]
I'll be pushing updates regularly, please file issues in github if you spot them.

**Comment by 0-afflatus** [comment]
Sure

**Comment by 0-afflatus** [comment]
:+1:  it works well and no complaints from players as yet.

**Comment by sofar** [comment]
I've made a minor change: until recently this mod would kill idle players. I've made it such that you lose stamina slowly, but not so much that it actually kills players.

**Comment by 0-afflatus** [comment]
Thanks @sofar I saw that and I've integrated the latest version into grailtest now.
